#!/usr/bin/env nu
# Clean Hydra build artifacts.
#
# Removes transient build outputs: Stack's .stack-work directories,
# Python virtual environments (.venv), and the Java/Gradle build cache.
# Does NOT remove generated sources under dist/ — those are checked in
# or regenerated by sync.
#
# Usage (from repo root):
#   nu pixi-scripts/clean.nu

def main [] {
    print "Cleaning Hydra build artifacts..."
    print ""

    # Haskell: Stack build caches
    for dir in ["heads/haskell/.stack-work", "packages/hydra-ext/.stack-work"] {
        if ($dir | path exists) {
            print $"  Removing ($dir)..."
            rm -rf $dir
        }
    }

    # Python: virtual environment and pytest cache
    for dir in ["heads/python/.venv", "heads/python/.pytest_cache"] {
        if ($dir | path exists) {
            print $"  Removing ($dir)..."
            rm -rf $dir
        }
    }

    # Java: Gradle build outputs
    if ("heads/java/build" | path exists) {
        print "  Removing heads/java/build..."
        rm -rf heads/java/build
    }

    # Scala: sbt build outputs
    for dir in ["heads/scala/target", "heads/scala/project/target"] {
        if ($dir | path exists) {
            print $"  Removing ($dir)..."
            rm -rf $dir
        }
    }

    # Root-level build directory
    if ("build" | path exists) {
        print "  Removing build/..."
        rm -rf build
    }

    print ""
    print "Clean complete."
}
